---
ansy_systemd_timers_working_dir: /home/yoshi/homelab-ansible
ansy_systemd_timers_run_user: yoshi
ansy_systemd_timers_playbook_bin: /usr/bin/ansible-playbook

systemd_ansible_timers:
  - name: authy-healthcheck
    description: Run authy healthcheck
    schedule: "*-*-* 05:30:00"
    playbook: playbooks/radius_healthcheck.yml
    persistent: true
  - name: proxmox-healthcheck
    description: Run Proxmox healthcheck
    schedule: "*-*-* 05:40:00"
    playbook: playbooks/proxmox_healthcheck.yml
    persistent: true
  - name: proxmox-patch-dryrun
    description: Run Proxmox patch dry-run
    schedule: "Fri *-*-* 17:30:00"
    playbook: playbooks/proxmox_patch_dryrun.yml
    persistent: true
  - name: authy-reboot-if-required
    description: Reboot authy if required
    schedule: "*-*-* 03:30:00"
    playbook: playbooks/ubuntu_nightly.yml
    persistent: false
  - name: proxmox-hw-check
    description: Run Proxmox hardware check
    schedule: "*-*-* 05:45:00"
    playbook: playbooks/proxmox_hw_check.yml
    persistent: true
