#!/bin/bash
# ansible-timer-failure-capture.sh — OnFailure= handler for units generated by
# roles/systemd_timers (nonsemaphore_job_capture案件, requirement R8).
#
# 起動経路: roles/systemd_timers/templates/ansible-timer.service.j2 の
# OnFailure=ansible-timer-failure-capture@%n.service により、生成された
# 各serviceがfailed状態に入るたびsystemdがこのunitを起動する。%iには失敗した
# unit名がそのまま渡る(ExecStartの引数。ansible-timer-failure-capture@.service.j2
# 参照)。flockが多重起動を排他した場合(exit 75)はSuccessExitStatus=75により
# unitがfailedに入らないため、このハンドラは呼ばれない(AC2)。
#
# 設計の要点(判断根拠。docs/ai/reviews/nonsemaphore_job_capture/
# 2026-08-05_002_implement.md参照):
#
#  1. 収集器が配備されているホストでだけ書く。ゲートに使うのは
#     roles/common_slack/tasks/capture.yml (T1)と同一のマーカーファイル
#     (/etc/homelab-recovery/incident-capture.json、
#     roles/incident_capture の incident_capture_config_path 既定値と同じ)。
#     無ければ何もせず exit 0(このホストに収集器が無い=書いても誰も読まない)。
#
#  2. spool_dirはそのマーカーファイル自身の "spool_dir" キーから読む。
#     roles/incident_capture/templates/incident-capture.json.j2 が書く値と
#     同じものであり、T1(capture.yml)の既定値とも一致する。値を
#     このスクリプト側で二重管理しない(ずれるとT1が書く場所と収集器が
#     読む場所が食い違う)。
#
#     **暗黙の依存(独立レビューSuggestion #2、2026-08-05指摘)**: このスクリプト
#     はspool_dirを自分では作らない(T1のように`mkdir`しない) — ディレクトリが
#     既に存在することを前提にしている。この前提は現状真である:
#     `roles/incident_capture/tasks/main.yml`の「Ensure reports/incidents/_spool/
#     exists」taskが、T1(capture.yml)より先にせよ後にせよ、incident_captureの
#     デプロイ時にディレクトリを作成・所有権を確定させる(T1自身も無ければ
#     作る保険を持つ)。**もしincident_captureのデプロイ順序が変わり、この
#     ハンドラが初めて発火する時点でまだ一度もincident_capture/T1が実行
#     されていない場合、このハンドラは何も書かずに静かにexit 0する**
#     (下の`-d "$SPOOL_DIR"`チェックがそのまま失敗するため)。マーカーファイル
#     (`/etc/homelab-recovery/incident-capture.json`)の存在自体が
#     incident_captureのデプロイ完了を意味するため、通常この経路には
#     入らないはずだが、**マーカーファイルの配備とspoolディレクトリの
#     作成が将来分離された場合はこの前提が崩れる**。ここでは意図的に
#     `mkdir`しない(このハンドラの権限・実行identityをT1と同じ最小限に保つ
#     ため、書き込み対象を「既存のディレクトリへのファイル追加」だけに
#     限定する)。
#
#  3. 書くレコードの形は roles/common_slack/tasks/capture.yml の
#     record_version 1 契約に厳密に合わせる。REQUIRED_SPOOL_FIELDSを1つも
#     欠かさないことを確認済み
#     (roles/incident_capture/files/incident-capture-collector.py
#     load_spool_record())。契約どおりに書けば、対応するSemaphoreジョブ行が
#     無いレコードは収集器の「相関しなかったspoolのうちnotableなもの」経路
#     (同ファイルmain()のstep 4)がそのまま単独バンドル(source: "spool")
#     として扱い、収集器はクラッシュしない — ローカルで
#     incident-capture-collector.py を直接実行し、この経路が実際に
#     source:"spool"のbundleを作ってexit 2(collection_errorsあり、
#     3=内部例外ではない)で終わることを確認済み(AC3)。
#
#  4. Slackは送らない(捕捉であって通知の新設ではない。requirement §4
#     非ゴール)。slack_status は "error"(収集器がnotableと判定する条件)に
#     するが、実際にSlackへ送信する経路はこのスクリプトには無い。
#
#  5. 失敗しても静かに諦める(exit 0)。このunit自身はOnFailure=を持たない
#     ため理論上は連鎖しないが、念のため単体でも安全側に倒す。
#
# skills/ansible-implementation-style/SKILL.md「shellは小規模ユーティリティに
# 限定」の範囲内(実処理は50行未満)。JSON組み立てはpython3に委ねる
# (日本語混じりの自由文をシェルで手組みクォートしない —
# roles/worktree_sync/templates/worktree-sync.sh.j2のnotify()と同じ理由)。
# 時刻は skills/ansible-implementation-style/SKILL.md の規約どおり
# `TZ='Asia/Tokyo' date '+%Y-%m-%dT%H:%M:%S+09:00'`(変換してからリテラルを
# 付けており、詐称ではない)。

set -uo pipefail

UNIT="${1:-unknown}"
CONFIG_PATH=/etc/homelab-recovery/incident-capture.json

# 収集器が配備されていなければ何もしない(T1と同じゲート条件)。
[[ -r "$CONFIG_PATH" ]] || exit 0

SPOOL_DIR=$(python3 -c '
import json, sys
try:
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        print(json.load(f)["spool_dir"])
except Exception:
    pass
' "$CONFIG_PATH")
# 依存: このディレクトリは roles/incident_capture がデプロイ時に作る前提。
# このスクリプトはmkdirしない(上のヘッダコメント「暗黙の依存」参照)。
# 前提が崩れている(未作成)場合は、書かずに静かに諦める。
[[ -n "$SPOOL_DIR" && -d "$SPOOL_DIR" ]] || exit 0

RECORD_ID="$(date +%s)-$(od -An -N4 -tx1 /dev/urandom | tr -d ' \n')"
WRITTEN_AT="$(TZ='Asia/Tokyo' date '+%Y-%m-%dT%H:%M:%S+09:00')"
CONTROLLER="$(hostname -s)"
DEST="$SPOOL_DIR/${RECORD_ID}.json"
TMP="${DEST}.tmp.$$"

UNIT="$UNIT" RECORD_ID="$RECORD_ID" WRITTEN_AT="$WRITTEN_AT" CONTROLLER="$CONTROLLER" \
  python3 -c '
import json
import os

unit = os.environ["UNIT"]
print(json.dumps({
    "record_version": 1,
    "id": os.environ["RECORD_ID"],
    "written_at": os.environ["WRITTEN_AT"],
    "controller": os.environ["CONTROLLER"],
    "play_name": unit,
    "play_host": os.environ["CONTROLLER"],
    "slack_channel": "",
    "slack_status": "error",
    "slack_title": "systemd unit failed: " + unit,
    "slack_message": (
        unit + " exited abnormally outside of Semaphore "
        "(roles/systemd_timers OnFailure= capture). "
        "See journalctl -u " + unit + " on this host."
    ),
    "skip_notifications": True,
    "check_mode": False,
}))
' > "$TMP" 2>/dev/null || { rm -f "$TMP"; exit 0; }

mv -f "$TMP" "$DEST" 2>/dev/null || rm -f "$TMP"
exit 0
