---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart recovery-slack-listener
  ansible.builtin.systemd:
    name: recovery-slack-listener
    state: restarted
  become: true
