---
all:
  children:
    proxmox:
      hosts:
        pve1:
          ansible_host: pve1.internal
        pve2:
          ansible_host: pve2.internal

    radius_servers:
      hosts:
        authy:
          ansible_host: authy.internal

    monitoring_servers:
      hosts:
        monnie:
          ansible_host: monnie.internal

    control_nodes:
      hosts:
        quory:
          ansible_host: quory.internal

    dev_nodes:
      hosts:
        ansy:
          ansible_host: ansy.internal

    semaphore_servers:
      hosts:
        ansy:
        quory:

    sophos:
      hosts:
        sophos:
          ansible_host: sophos-fw.internal
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_sophos
          ansible_connection: ssh

    local:
      hosts:
        localhost:
          ansible_connection: local
