---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart recovery-io
  ansible.builtin.systemd:
    name: recovery-io
    state: restarted
  become: true
